include:
  - project: $INCLUDE_PROJECT
    file: '/templates/gitlab/base.yml'

image: registry.znuny.com/znuny/internal/docker-znunylts-ci:test-stable

stages:
  - utils
  - check
  - unittest
  - deploy

GitHub:
  extends: .deploy_github
